// this file should be generated by MegCC
#ifndef KERNEL_H
#define KERNEL_H

#include "data_struct.h"
#include "stdint.h"
#include "string.h"

#define NR_KERNELS      (12)
#define NR_INIT         (12)
#define NR_DEDUCE_SHAPE (1)
#define NR_WORKSPACE    (0)

#define KERNEL_MARK_USDED_VAR(x) (void)(x);

extern KernelFunc kernels[NR_KERNELS];

extern InitFunc init_kernels[NR_INIT];
extern WorkspaceFunc workspace_func[NR_WORKSPACE];
extern DeduceFunc deduce_func[NR_DEDUCE_SHAPE];

void load_kernel_init_function();
#endif
//! declare all the kernel here in C
