name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  NDK_ROOT: /root/android-ndk-r21
  RISCV_TOOLCHAIN_ROOT: /root/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.2.6/

jobs:
  test_compiler:
    runs-on: self-hosted
    timeout-minutes: 240
    container:
      image: mcd.io/mcd-apps/megcc-ci:v1
    steps:
      - name: Checkout MegCC
        uses: actions/checkout@v3
      - name: Prepare env
        run: ./ci/prepare.sh /root/llvm-project
      - name: Cmake build MegCC
        run: ./compiler/script/ci/run_local_cmake_build.sh ./compiler/local_cmake_build  /root/llvm-project
      - name: Regression test
        run: ./compiler/script/ci/run_local_regression_test.sh ./compiler/local_cmake_build

  test_kernel:
    runs-on: self-hosted
    timeout-minutes: 240
    container:
      image: mcd.io/mcd-apps/megcc-ci:v1
      env:
        KOROK_BUCKET: ${{ secrets.KOROK_BUCKET }}
        KOROK_GROUP: ${{ secrets.KOROK_GROUP }}
        KOROK_SERVER: ${{ secrets.KOROK_SERVER }}
        KOROK_TOKEN: ${{ secrets.KOROK_TOKEN }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
        OSS_EXTERNAL_ENDPOINT: ${{ secrets.OSS_EXTERNAL_ENDPOINT }}
        OSS_SECRET_ACCESS_KEY: ${{ secrets.OSS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout MegCC
        uses: actions/checkout@v3
      - name: Prepare env
        run: ./ci/prepare.sh /root/llvm-project
      - name: Cmake build and run kernel test
        run: ./compiler/script/ci/run_local_kernel_ut.sh ./compiler/kernel_ut_x86_64 /root/llvm-project
      - name: Cmake build and run instruction test
        run: ./runtime/scripts/run_local_instruction_test.sh
